version: "3.8"
services:
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    container_name: mysql
    command: ['--default-authentication-plugin=mysql_native_password']
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      TZ: "${TIMEZONE}"
    ports:
      - "${DB_PORT}:3306"

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 100000000 

  laravel: 
    build: ./
    container_name: laravel
    environment:
      TZ: "${TIMEZONE}"
    #volumes:
    #  - ./laravel-app/:/app/
    ports:
      - "${LARAVEL_PORT}:80"
    #command: sh -c "composer install --no-interaction --optimize-autoloader --no-dev && npm install && yarn install && yarn build && php artisan config:cache && php artisan route:cache && php artisan view:cache"

volumes:
    db_data:
    laravel-app: